version: '3.8'

services:
  # Layanan untuk Oracle XE
  db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-new
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: yourpassword
      ORACLE_DATABASE: XEPDB8
  # Layanan untuk aplikasi Go
  golang-ora:
    build:
      context: .
    container_name: golang-ora
    ports:
      - "3000:3000" 
    environment:
      - DB_USER=system
      - DB_PASSWORD=yourpassword
      - DB_HOST=db
      - DB_PORT=1521
      - DB_SID=XEPDB8
    depends_on:
      - db
    command: ["sh", "-c", "sleep 60 && go run main.go"] # Menggabungkan penundaan dengan perintah untuk menjalankan aplikasi Go
volumes:
  oracle-data:
    driver: local
